spring.application.name=devsecops-challenge-microservicio
server.port=8080

# Actuator: solo se exponen health e info, no se exponen endpoints sensibles
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
