name: "Develop"

on:
  push:
    branches: [develop]
  
  pull_request:
    branches: [develop]

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  pipeline:
    name: "Ejecutando el pipeline completo hacia dev"
    uses: anakarina1928/devsecops-shared-workflows-challenge/.github/workflows/template-orchestrator.yml@main
    with:
      environment: dev
      namespace: dev
      registry: devsecopschallenge2026.azurecr.io
      image-name: microservicio
      image-tag: ${{ github.sha }}
      resource-group: rg-devsecops-challenge
      aks-cluster-name: aks-devsecops-challenge-ana
    secrets: inherit
